### ISSUE TITLE
difference in schema definition between FHIR R4 and dbingite resources.

### ISSUE THREAD

**Issue by aashish-sapkota-abacus** [databrickslabs/dbignite#39]
As per the comparison between the FHIR R4 and dbignite schema, we have found the differences in following resources : 

**Composition** 
- identifier 
- subject

**Encounter** 
- class
- diagnosis.condition
-  diagnosis.use
-  serviceType

**MedicationStatement** 
-  informationSource

Please refer to the detailed schema comparison in the attachment:
[FHIR vs dbignite schema comparision.xlsx](https://github.com/databrickslabs/dbignite/files/14140482/FHIR.vs.dbignite.schema.comparision.xlsx)

**Comment by zavoraad** [comment]
Hi @aashish-sapkota-abacus , can you describe what differences you are seeing and the expected values? 

e.g. I see Encounter.class defined as an Array in both Spark & HL7 International schemas. Composition.identifier as an Array in both Spark & HL7 International schemas. Same with MedicationStatement.informationSource.

HL7 international referenced schema is [here](https://build.fhir.org/downloads.html)

**Comment by zavoraad** [comment]
Hi @aashish-sapkota-abacus , closing this issue given no response. If it is still an issue we can reopen and get more detail.

**Comment by aashish-sapkota-abacus** [comment]
Thank you Aaron,

-aashish
________________________________
