### ISSUE TITLE
Encountering issue when running install

### ISSUE THREAD

**Issue by jabeenstudy** [databrickslabs/dbignite#43]
pip install git+https://github.com/databrickslabs/dbignite.git                       
Collecting git+https://github.com/databrickslabs/dbignite.git
  Cloning https://github.com/databrickslabs/dbignite.git to /private/var/folders/w8/wk1tpwvj6wv_fq0ltx90ng85j3k87_/T/pip-req-build-ik88df9f
  Running command git clone --filter=blob:none --quiet https://github.com/databrickslabs/dbignite.git /private/var/folders/w8/wk1tpwvj6wv_fq0ltx90ng85j3k87_/T/pip-req-build-ik88df9f
  Resolved https://github.com/databrickslabs/dbignite.git to commit ce29f581f8e13096f56dd1887dff934bcef72da3
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in dbignite setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.9.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
### **setup.py invalid version specification**
[https://packaging.python.org/en/latest/specifications/version-specifiers/#version-matching](url)
from setuptools import setup
from io import open
from os import path
import sys

DESCRIPTION = "Package for ingesting FHIR bunldes in deltalake"
this_directory = path.abspath(path.dirname(__file__))

with open(path.join(this_directory, "README.md"), encoding="utf-8") as f:
    LONG_DESCRIPTION = f.read()

try:
    exec(open("dbignite/version.py").read())
except IOError:
    print("Failed to load version file for packaging.", file=sys.stderr)
    sys.exit(-1)
VERSION = __version__

setup(
    name="dbignite",
    version=VERSION,
    **python_requires='>=3.9.*',**
    author="Amir Kermany, Nathan Buesgens, Rachel Sim, Aaron Zavora, William Smith, Jesse Young",
    author_email="labs@databricks.com",
    description= DESCRIPTION,
    long_description=LONG_DESCRIPTION,
    long_description_content_type="text/markdown",
    url="https://github.com/databrickslabs/dbignite",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: Other/Proprietary License",
        "Operating System :: OS Independent",
    ],
    packages=['dbignite', 'dbignite.omop', 'dbignite.hosp_feeds'],
    package_data={'': ["schemas/*.json"]},
    py_modules=['dbignite.data_model']
)

**Comment by zavoraad** [comment]
Hi @jabeenstudy, it looks like some versions of pip & setuptools have strict adherence on Python versions using the ">=" symbol. 

I've created a new branch to fix this. Can you see if installing from this branch works and let me know if this works? 

`pip install git+https://github.com/databrickslabs/dbignite.git@hotfix-43
`

**Comment by jabeenstudy** [comment]
able to install
Collecting git+https://github.com/databrickslabs/dbignite.git@hotfix-43
  Cloning https://github.com/databrickslabs/dbignite.git (to revision hotfix-43) to /tmp/pip-req-build-gs1cpw_t
  Running command git clone --filter=blob:none --quiet https://github.com/databrickslabs/dbignite.git /tmp/pip-req-build-gs1cpw_t
  Running command git checkout -b hotfix-43 --track origin/hotfix-43
  Switched to a new branch 'hotfix-43'
  Branch 'hotfix-43' set up to track remote branch 'hotfix-43' from 'origin'.
  Resolved https://github.com/databrickslabs/dbignite.git to commit 6bace7594edf79de8acd731d7bba2345756200b5
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dbignite
  Building wheel for dbignite (setup.py) ... done
  Created wheel for dbignite: filename=dbignite-0.2.3-py3-none-any.whl size=3101407 sha256=28e3f7e915ce6cbe81cd6376f8a2857862cfc07d421c5ac49d321fee2865d260
  Stored in directory: /tmp/pip-ephem-wheel-cache-i7_jkaoo/wheels/a4/b4/bc/baf5d325e65d2ef0779bc522da30246e580682f95d4780d9c1
Successfully built dbignite
Installing collected packages: dbignite
Successfully installed dbignite-0.2.3
